/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rk.javabnb.Inmuebles;

import com.rk.javabnb.UI.DatosBancarios;
import com.rk.javabnb.Usuarios.Cliente;
import com.rk.javabnb.Usuarios.ClienteParticular;
import com.rk.javabnb.db.Database;

import javax.swing.*;
import javax.swing.event.ListDataListener;
import java.time.LocalDate;
import java.util.ArrayList;

/**
 *
 * @author Roberto
 */
public class PreReserva extends javax.swing.JFrame {
    private Inmueble inmueble;
    /**
     * Creates new form PreReserva
     */
    public PreReserva(Inmueble i) {
        initComponents();
        this.setVisible(true);

        this.titulo.setText(i.getNombre());
        this.direccion.setText(i.getDireccion());
        this.desc.setText(i.getDesc());
        this.foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+this.titulo.getText()+".png")));
        this.calificacion.setText(i.getCalificacion() + "/5");
        this.precio.setText(i.getPrecio() + "€");
        DefaultListModel<String> modeloServicios = new DefaultListModel<>();
        for(String m : i.getServicios()) { modeloServicios.addElement(m); }
        this.servicios.setModel(modeloServicios);

        DefaultListModel<String> modeloDatos = new DefaultListModel<>();
        for(String s : i.getDatos()) { modeloDatos.addElement(s); }
        this.datos.setModel(modeloDatos);
        this.tipo.setText(i.getTipo());

    }

    /**O
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPanel = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        calificacion = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        reservar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        datos = new javax.swing.JList<>();
        fechaEntrada = new javax.swing.JFormattedTextField();
        fechaSalida = new javax.swing.JFormattedTextField();
        comentario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        huespedesNum = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reservar");
        setMinimumSize(new java.awt.Dimension(650, 450));
        setPreferredSize(new java.awt.Dimension(650, 450));

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.GridBagLayout());

        titulo.setFont(new java.awt.Font("Montserrat", 3, 36)); // NOI18N
        titulo.setText("Casa Roberto");
        contentPanel.add(titulo, new java.awt.GridBagConstraints());

        tipo.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        tipo.setText("tipo");
        contentPanel.add(tipo, new java.awt.GridBagConstraints());

        direccion.setFont(new java.awt.Font("Montserrat Light", 2, 24)); // NOI18N
        direccion.setText("C/Belvis");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        contentPanel.add(direccion, gridBagConstraints);

        foto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(foto, gridBagConstraints);

        calificacion.setFont(new java.awt.Font("Montserrat", 2, 24)); // NOI18N
        calificacion.setText("CALIF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        contentPanel.add(calificacion, gridBagConstraints);

        precio.setFont(new java.awt.Font("Montserrat", 2, 36)); // NOI18N
        precio.setText("800@");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        contentPanel.add(precio, gridBagConstraints);

        desc.setFont(new java.awt.Font("Montserrat", 2, 18)); // NOI18N
        desc.setText("Casa coquette");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(desc, gridBagConstraints);

        reservar.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        reservar.setLabel("Reservar");
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        contentPanel.add(reservar, gridBagConstraints);

        servicios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(servicios);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(jScrollPane1, gridBagConstraints);

        datos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(datos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        contentPanel.add(jScrollPane2, gridBagConstraints);

        try {
            fechaEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        contentPanel.add(fechaEntrada, gridBagConstraints);

        try {
            fechaSalida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        contentPanel.add(fechaSalida, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 11);
        contentPanel.add(comentario, gridBagConstraints);

        jLabel1.setText("Fecha de entrada:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 5, 0);
        contentPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Fecha de salida:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 5, 0);
        contentPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Comentario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 7, 5, 7);
        contentPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Huéspedes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        contentPanel.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        contentPanel.add(huespedesNum, gridBagConstraints);

        scrollPanel.setViewportView(contentPanel);

        getContentPane().add(scrollPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed

        if((int) this.huespedesNum.getValue() == 0) {
            JOptionPane.showMessageDialog(this, "Debes tener al menos 1 huesped", "Error", JOptionPane.WARNING_MESSAGE);
        }

        ClienteParticular reservador = (ClienteParticular) Database.getCurrentUser().get(0);

        if(reservador.getTarjeta() == null) {
            JOptionPane.showMessageDialog(this, "No tienes configurado ningún método de pago", "Error de pago", JOptionPane.WARNING_MESSAGE);
            new DatosBancarios();
        }

        String[] fEntrada = new String[3];
        fEntrada = fechaEntrada.getText().split("/");
        String[] fSalida = new String[3];
        fSalida = fechaSalida.getText().split("/");

        LocalDate fEntradaFormat = LocalDate.of(Integer.parseInt(fEntrada[2]),Integer.parseInt(fEntrada[1]), Integer.parseInt(fEntrada[0]));
        LocalDate fSalidaFormat = LocalDate.of(Integer.parseInt(fSalida[2]),Integer.parseInt(fSalida[1]), Integer.parseInt(fSalida[0]));

        new Reserva(this.inmueble, (Cliente) Database.getCurrentUser().get(0), this.comentario.getText(), fEntradaFormat, fSalidaFormat, (int) this.huespedesNum.getValue());
    }//GEN-LAST:event_reservarActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreReserva().setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calificacion;
    private javax.swing.JTextField comentario;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JList<String> datos;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel direccion;
    private javax.swing.JFormattedTextField fechaEntrada;
    private javax.swing.JFormattedTextField fechaSalida;
    private javax.swing.JLabel foto;
    private javax.swing.JSpinner huespedesNum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel precio;
    private javax.swing.JButton reservar;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JList<String> servicios;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
