/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rk.javabnb.UI;

import com.rk.javabnb.db.Database;

import javax.swing.*;

/**
 *
 * @author admin
 */
public class MenuAnfitrion extends javax.swing.JFrame {

    /**
     * Creates new form MenuAnfitrion
     */
    public MenuAnfitrion() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setSize(1000, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        anadirInmuebleButton = new javax.swing.JButton();
        verReservasButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        misInmueblesButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        perfilButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formClosing();
            }
        });
        this.getContentPane().setLayout(new java.awt.GridBagLayout());
        this.setBackground(new java.awt.Color(255, 255, 255));

        anadirInmuebleButton.setText("Añadir inmueble");
        anadirInmuebleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirInmuebleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(anadirInmuebleButton, gridBagConstraints);

        verReservasButton.setText("Ver reservas");
        verReservasButton.setMaximumSize(new java.awt.Dimension(128, 27));
        verReservasButton.setMinimumSize(new java.awt.Dimension(128, 27));
        verReservasButton.setPreferredSize(new java.awt.Dimension(128, 27));
        verReservasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReservasButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        getContentPane().add(verReservasButton, gridBagConstraints);

        volverButton.setText("Cerrar sesión");
        volverButton.setMaximumSize(new java.awt.Dimension(128, 27));
        volverButton.setMinimumSize(new java.awt.Dimension(128, 27));
        volverButton.setPreferredSize(new java.awt.Dimension(128, 27));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        getContentPane().add(volverButton, gridBagConstraints);

        jLabel1.setText("           ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("           ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("           ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("           ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel5, gridBagConstraints);

        jLabel6.setText("     ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel6, gridBagConstraints);

        misInmueblesButton.setText("Ver inmuebles");
        misInmueblesButton.setMaximumSize(new java.awt.Dimension(128, 27));
        misInmueblesButton.setMinimumSize(new java.awt.Dimension(128, 27));
        misInmueblesButton.setPreferredSize(new java.awt.Dimension(128, 27));
        misInmueblesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misInmueblesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(misInmueblesButton, gridBagConstraints);

        jLabel7.setText("           ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel7, gridBagConstraints);

        perfilButton.setText("Perfil");
        perfilButton.setMaximumSize(new java.awt.Dimension(128, 27));
        perfilButton.setMinimumSize(new java.awt.Dimension(128, 27));
        perfilButton.setPreferredSize(new java.awt.Dimension(128, 27));
        perfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        getContentPane().add(perfilButton, gridBagConstraints);

        jLabel8.setText("           ");
        jLabel8.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel8, gridBagConstraints);

        jLabel9.setText("Anfitrion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel9, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verReservasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReservasButtonActionPerformed
        new HomeReservas("anfitrion");
        this.dispose();
        this.setVisible(false);
        //le enseña al anfitrion todas las reservas de sus inmuebles
    }//GEN-LAST:event_verReservasButtonActionPerformed

    private void misInmueblesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misInmueblesButtonActionPerformed
        new Home("anfitrion");
        this.dispose();
        this.setVisible(false);
        //muestra todos los inmuebles del anfitrion
    }//GEN-LAST:event_misInmueblesButtonActionPerformed

    private void anadirInmuebleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirInmuebleButtonActionPerformed
        new CrearInmueble();
        this.dispose();
        this.setVisible(false);
        //abre la pagina de crear inmueble
    }//GEN-LAST:event_anadirInmuebleButtonActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        Database.cerrarSesion();
        new Login();
        this.dispose();
        this.setVisible(false);
        //cierra la sesion
    }//GEN-LAST:event_volverButtonActionPerformed

    private void perfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilButtonActionPerformed
        new PerfilAnfitrion();
        this.dispose();
        this.setVisible(false);
        //abre la pagina con los datos del anfitrion, que puede editar si quiere
    }//GEN-LAST:event_perfilButtonActionPerformed
 
    private void formClosing() { new Home("anfitrion"); this.dispose(); }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAnfitrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAnfitrion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirInmuebleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton misInmueblesButton;
    private javax.swing.JButton perfilButton;
    private javax.swing.JButton verReservasButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
