/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rk.javabnb.UI;

import javax.swing.*;

/**
 *
 * @author admin
 */
public class MenuParticular extends javax.swing.JFrame {

    /**
     * Creates new form MenuParticular
     */
    public MenuParticular() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        logoLabel = new javax.swing.JLabel();
        dejarResenaButton = new javax.swing.JButton();
        perfilButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        verReservasButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formClosing();
            }
        });
        this.getContentPane().setLayout(new java.awt.GridBagLayout());
        this.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_logo.png"))); // NOI18N
        logoLabel.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(logoLabel, gridBagConstraints);

        dejarResenaButton.setText("Dejar reseña");
        dejarResenaButton.setMaximumSize(new java.awt.Dimension(120, 27));
        dejarResenaButton.setMinimumSize(new java.awt.Dimension(120, 27));
        dejarResenaButton.setPreferredSize(new java.awt.Dimension(120, 27));
        dejarResenaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dejarResenaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(dejarResenaButton, gridBagConstraints);

        perfilButton.setText("Perfil");
        perfilButton.setMaximumSize(new java.awt.Dimension(120, 27));
        perfilButton.setMinimumSize(new java.awt.Dimension(120, 27));
        perfilButton.setPreferredSize(new java.awt.Dimension(120, 27));
        perfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        getContentPane().add(perfilButton, gridBagConstraints);

        volverButton.setText("Ver inmuebles");
        volverButton.setToolTipText("");
        volverButton.setMaximumSize(new java.awt.Dimension(120, 27));
        volverButton.setMinimumSize(new java.awt.Dimension(120, 27));
        volverButton.setPreferredSize(new java.awt.Dimension(120, 27));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        getContentPane().add(volverButton, gridBagConstraints);

        jLabel1.setText("        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel4, gridBagConstraints);

        jLabel5.setText("        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel5, gridBagConstraints);

        verReservasButton.setText("Ver reservas");
        verReservasButton.setMaximumSize(new java.awt.Dimension(120, 27));
        verReservasButton.setMinimumSize(new java.awt.Dimension(120, 27));
        verReservasButton.setPreferredSize(new java.awt.Dimension(120, 27));
        verReservasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReservasButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        getContentPane().add(verReservasButton, gridBagConstraints);

        jLabel6.setText("        ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel6, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dejarResenaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dejarResenaButtonActionPerformed
        new HomeReservas("particular");
        this.dispose();
        this.setVisible(false);
        //le muestra la pagina con sus reservas, donde puede valorar el inmueble que ha reservado
    }//GEN-LAST:event_dejarResenaButtonActionPerformed

    private void verReservasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReservasButtonActionPerformed
        new HomeReservas("particular");
        this.dispose();
        this.setVisible(false);
        //le muestra todas sus reservas
    }//GEN-LAST:event_verReservasButtonActionPerformed

    private void perfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilButtonActionPerformed
        new PerfilParticular();
        this.dispose();
        this.setVisible(false);
        //lleva a la pagina con datos del cliente, donde los puede editar
    }//GEN-LAST:event_perfilButtonActionPerformed

    private void formClosing() { new Home("particular"); this.dispose(); }
    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        new Home("particular");
        this.dispose();
        this.setVisible(false);
        //vuelve a la pagina que se abre automaticamente al loggearse, a todos los inmuebles
    }//GEN-LAST:event_volverButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuParticular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dejarResenaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton perfilButton;
    private javax.swing.JButton verReservasButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
