/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rk.javabnb.UI;

import com.rk.javabnb.Usuarios.ClienteParticular;
import com.rk.javabnb.db.DataChecker;
import com.rk.javabnb.db.Database;

import javax.swing.*;

/**
 *
 * @author admin
 */
public class PerfilParticular extends javax.swing.JFrame {

    /**
     * Creates new form PerfilPatricular
     */
    public PerfilParticular() {
        setVisible(true);
        this.particular = Database.getCurrentParticular();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(1000, 1000);
        //aqui el cliente puede ver y modificar sus datos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        telefonoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dniTextField = new javax.swing.JTextField();
        hacerseVIPButton = new javax.swing.JButton();
        cambiarContrasenaButton = new javax.swing.JButton();
        menuButton = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tarjetaTextField = new javax.swing.JTextField();
        cambiarTarjetaButton = new javax.swing.JButton();

        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.getContentPane().setLayout(new java.awt.GridBagLayout());
        this.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nombre:");
        jLabel2.setMaximumSize(new java.awt.Dimension(151, 27));
        jLabel2.setMinimumSize(new java.awt.Dimension(151, 27));
        jLabel2.setPreferredSize(new java.awt.Dimension(151, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabel2, gridBagConstraints);

        nombreTextField.setText(particular.getNombre());
        nombreTextField.setMinimumSize(new java.awt.Dimension(344, 27));
        nombreTextField.setPreferredSize(new java.awt.Dimension(344, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        getContentPane().add(nombreTextField, gridBagConstraints);

        jLabel3.setText("Email:");
        jLabel3.setMaximumSize(new java.awt.Dimension(151, 27));
        jLabel3.setMinimumSize(new java.awt.Dimension(151, 27));
        jLabel3.setPreferredSize(new java.awt.Dimension(151, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabel3, gridBagConstraints);

        emailTextField.setText(particular.getEmail());
        emailTextField.setMinimumSize(new java.awt.Dimension(344, 27));
        emailTextField.setPreferredSize(new java.awt.Dimension(344, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        getContentPane().add(emailTextField, gridBagConstraints);

        jLabel4.setText("Teléfono:");
        jLabel4.setMaximumSize(new java.awt.Dimension(151, 27));
        jLabel4.setMinimumSize(new java.awt.Dimension(151, 27));
        jLabel4.setPreferredSize(new java.awt.Dimension(151, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel4, gridBagConstraints);

        telefonoTextField.setText(particular.getTelefono());
        telefonoTextField.setMinimumSize(new java.awt.Dimension(344, 27));
        telefonoTextField.setPreferredSize(new java.awt.Dimension(344, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        getContentPane().add(telefonoTextField, gridBagConstraints);

        jLabel5.setText("DNI:");
        jLabel5.setMaximumSize(new java.awt.Dimension(151, 27));
        jLabel5.setMinimumSize(new java.awt.Dimension(151, 27));
        jLabel5.setPreferredSize(new java.awt.Dimension(151, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabel5, gridBagConstraints);

        dniTextField.setText(particular.getDni());
        dniTextField.setMinimumSize(new java.awt.Dimension(344, 27));
        dniTextField.setPreferredSize(new java.awt.Dimension(344, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        getContentPane().add(dniTextField, gridBagConstraints);

        hacerseVIPButton.setText("Quiero ser VIP");
        hacerseVIPButton.setMaximumSize(new java.awt.Dimension(151, 27));
        hacerseVIPButton.setMinimumSize(new java.awt.Dimension(151, 27));
        hacerseVIPButton.setPreferredSize(new java.awt.Dimension(151, 27));
        hacerseVIPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerseVIPButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 0, 0);
        getContentPane().add(hacerseVIPButton, gridBagConstraints);

        cambiarContrasenaButton.setText("Cambiar contraseña");
        cambiarContrasenaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContrasenaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
        getContentPane().add(cambiarContrasenaButton, gridBagConstraints);

        menuButton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {particular.getNombre(), "Guardar cambios y volver", "Volver sin guardar" }));
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(menuButton, gridBagConstraints);

        jLabel6.setText("Tarjeta:");
        jLabel6.setMaximumSize(new java.awt.Dimension(151, 27));
        jLabel6.setMinimumSize(new java.awt.Dimension(151, 27));
        jLabel6.setPreferredSize(new java.awt.Dimension(151, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(jLabel6, gridBagConstraints);

        tarjetaTextField.setText(particular.getTarjetaS());
        tarjetaTextField.setMinimumSize(new java.awt.Dimension(150, 27));
        tarjetaTextField.setPreferredSize(new java.awt.Dimension(150, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        getContentPane().add(tarjetaTextField, gridBagConstraints);

        cambiarTarjetaButton.setText("Cambiar la tarjeta");
        cambiarTarjetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarTarjetaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(cambiarTarjetaButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cambiarTarjetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarTarjetaButtonActionPerformed
        new DatosBancarios("perfil");
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_cambiarTarjetaButtonActionPerformed

    private void hacerseVIPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerseVIPButtonActionPerformed
        new VIP();
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_hacerseVIPButtonActionPerformed

    private void cambiarContrasenaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContrasenaButtonActionPerformed
        new NuevaContrasena();
        this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_cambiarContrasenaButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        switch (menuButton.getSelectedIndex()) {
            case 1:
                if(nombreTextField.getText().length()>0){
                    particular.setNombre(nombreTextField.getText());
                }else{
                    JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio", "Nombre vacío", JOptionPane.ERROR_MESSAGE);
                }
                if(emailTextField.getText().length()>0){
                    particular.setEmail(emailTextField.getText());
                }else{
                    JOptionPane.showMessageDialog(this, "El email no puede estar vacio", "Email vacío", JOptionPane.ERROR_MESSAGE);
                }
                if(DataChecker.checkDNI(dniTextField.getText())){
                    particular.setDni(dniTextField.getText());
                }else{
                    JOptionPane.showMessageDialog(this,"Introduzca un DNI válido","DNI incorrecto",JOptionPane.ERROR_MESSAGE);
                }
                if(DataChecker.checkTfn(telefonoTextField.getText())){
                    this.particular.setTelefono(Integer.parseInt(telefonoTextField.getText()));
                }else{
                    JOptionPane.showMessageDialog(this,"El número de teléfono tiene que tener nueve dígitos","Teléfono incorrecto",JOptionPane.ERROR_MESSAGE);
                }
                Database.save();
                new MenuParticular();
                this.dispose();
                this.setVisible(false);
                break;
                //se verifica que los datos que aparecen son validos (telefono valido, dni...), se guardan y se vuelve al menu
            case 2:
                new MenuParticular();
                this.dispose();
                this.setVisible(false);
                break;

        }
    }//GEN-LAST:event_menuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilParticular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilParticular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambiarContrasenaButton;
    private javax.swing.JButton cambiarTarjetaButton;
    private javax.swing.JTextField dniTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton hacerseVIPButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> menuButton;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField tarjetaTextField;
    private javax.swing.JTextField telefonoTextField;
    // End of variables declaration//GEN-END:variables
    private ClienteParticular particular;
}
