/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rk.javabnb.UI;

import com.rk.javabnb.Usuarios.Cliente;
import com.rk.javabnb.db.Database;

import javax.swing.*;

/**
 *
 * @author admin
 */
public class ReestablecerContrasena extends javax.swing.JFrame {

    /**
     * Creates new form ReestablecerContrasena
     */
    public ReestablecerContrasena() {
        this.setVisible(true);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        //esta pagina permite reestablecer la contraseña en el casi ficticio de que podriamos mandar correos a los usuarios, le llegaria un correo que iria a la pagina de Nueva contraseña y el usuario cambiaria su contraseña
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        volverButton = new javax.swing.JButton();
        reestablecerButton = new javax.swing.JButton();

        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formClosing();
            }
        });
        this.getContentPane().setLayout(new java.awt.GridBagLayout());
        this.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/small_logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(9, 21, 9, 21);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 15, 4, 15);
        getContentPane().add(jLabel2, gridBagConstraints);

        emailTextField.setMinimumSize(new java.awt.Dimension(150, 27));
        emailTextField.setPreferredSize(new java.awt.Dimension(150, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 13, 4, 13);
        getContentPane().add(emailTextField, gridBagConstraints);

        volverButton.setText("Volver");
        volverButton.setMaximumSize(new java.awt.Dimension(111, 27));
        volverButton.setMinimumSize(new java.awt.Dimension(111, 27));
        volverButton.setPreferredSize(new java.awt.Dimension(111, 27));
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 9, 12, 21);
        getContentPane().add(volverButton, gridBagConstraints);

        reestablecerButton.setText("Reestablecer");
        reestablecerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reestablecerButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 21, 12, 12);
        getContentPane().add(reestablecerButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reestablecerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reestablecerButtonActionPerformed
        boolean existe = true;
        if(!Database.getAllEmail().contains(emailTextField.getText())){
            JOptionPane.showMessageDialog(this, "El email no existe","Error",JOptionPane.ERROR_MESSAGE);
            existe = false;
        }
        if(existe) {
            JOptionPane.showMessageDialog(this, "En breve le llegará un email", "Reestableciendo contraseña", JOptionPane.INFORMATION_MESSAGE);
            new Login();
            this.dispose();
            this.setVisible(false);
        }
        //verifica que existe una cuenta vinculada al correo introducido y en el caso hipotetico desde aqui se mandaria un correo al cliente
    }//GEN-LAST:event_reestablecerButtonActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        new Login();
        this.dispose();
        this.setVisible(false);
        //vuelve a la pagina de login
    }//GEN-LAST:event_volverButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReestablecerContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReestablecerContrasena().setVisible(true);
            }
        });
    }
    private void formClosing() {
        Cliente c = (Cliente) Database.getCurrentUser().getFirst();
        new Login();
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton reestablecerButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
